# Generated by Django 5.2.8 on 2025-11-20 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Mesa')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de la Mesa')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación de la Mesa')),
                ('estado', models.BooleanField(default=False, verbose_name='Ocupada')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora de Pedido')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observación del Pedido')),
                ('CostoTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Total del Pedido')),
                ('estado_pedido', models.CharField(choices=[('ABIERTO', 'Abierto (Tomando orden)'), ('EN_ESPERA', 'En Espera (Enviado a cocina)'), ('PREPARADO', 'Listo para Servir'), ('CERRADO', 'Cerrado (Pagado)'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=15, verbose_name='Estado del Pedido')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Toma el Pedido')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Producto')),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario del Producto')),
                ('observacion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observación del Producto')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal del Producto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (En orden)'), ('COCINA', 'En Preparación'), ('SERVIDO', 'Servido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estado del Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del Pedido',
                'verbose_name_plural': 'Productos del Pedido',
                'db_table': 'producto_pedido',
            },
        ),
    ]
