# Generated by Django 5.2.7 on 2025-11-12 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Empleado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Toma el Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.mesa', verbose_name='Mesa'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto'),
        ),
    ]
