# Generated by Django 5.2.8 on 2025-11-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Empleado_id',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='mesa_id',
            new_name='mesa',
        ),
        migrations.RenameField(
            model_name='productopedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='productopedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Ocupada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='CostoTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Total del Pedido'),
        ),
    ]
