# Generated by Django 5.2.7 on 2025-11-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ABIERTO', 'Abierto (Tomando orden)'), ('EN_ESPERA', 'En Espera (Enviado a cocina)'), ('PREPARADO', 'Listo para Servir'), ('CERRADO', 'Cerrado (Pagado)'), ('ENTREGADO', 'Entregado al Cliente'), ('POR_FACTURAR', 'Por Facturar'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=15, verbose_name='Estado del Pedido'),
        ),
    ]
