# Generated by Django 5.2.7 on 2025-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(default=1, unique=True, verbose_name='Cédula'),
            preserve_default=False,
        ),
    ]
