# Generated by Django 5.2.7 on 2025-11-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cliente', 'Cliente')], default='mesero', max_length=20, verbose_name='Rol'),
        ),
    ]
