# Generated by Django 5.2.7 on 2025-11-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos/', verbose_name='Imagen del Producto')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponibilidad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria', verbose_name='Categoría del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
