# Generated by Django 5.2.7 on 2025-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('hora_emision', models.TimeField(auto_now_add=True, verbose_name='Hora de Emisión')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Impuesto')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('totalFactura', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total de la Factura')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
    ]
