# Generated by Django 5.2.7 on 2025-11-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('cliente_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula/RIF')),
                ('cliente_direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('numero_factura', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('hora_emision', models.TimeField(auto_now_add=True, verbose_name='Hora de Emisión')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Impuesto (%)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('totalFactura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la Factura')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
    ]
