# Generated by Django 5.2.8 on 2025-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula/RIF'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Impuesto (%)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='totalFactura',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la Factura'),
        ),
    ]
